const defaultDeck = [
  { name: "pen", image: "thumbs/pen.jpg", flipped: false },
  { name: "David", image: "thumbs/David.jpg", flipped: false },
  { name: "dog", image: "thumbs/dog.jpg", flipped: false },
  { name: "bird", image: "thumbs/bird.jpg", flipped: false },
  { name: "rat", image: "thumbs/rat.jpg", flipped: false },
  { name: "duck", image: "thumbs/duck.jpg", flipped: false },
  { name: "cheetah", image: "thumbs/cheetah.jpg", flipped: false },
  { name: "elephant", image: "thumbs/elephant.png", flipped: false },
  { name: "fish", image: "thumbs/fish.png", flipped: false },
  { name: "horse", image: "thumbs/horse.jpg", flipped: false },
  { name: "jellyfish", image: "thumbs/jellyfish.jpg", flipped: false },
  { name: "shark", image: "thumbs/shark.jpg", flipped: false },
  { name: "lion", image: "thumbs/lion.jpg", flipped: false },
  { name: "zebra", image: "thumbs/zebra.jpg", flipped: false },
  { name: "raccoon", image: "thumbs/raccoon.jpg", flipped: false },
  { name: "sparrow", image: "thumbs/sparrow.jpg", flipped: false },
  { name: "pikachu", image: "thumbs/pikachu.jpg", flipped: false },
  { name: "donut", image: "thumbs/donut.jpg", flipped: false },
  { name: "cheese", image: "thumbs/cheese.jpg", flipped: false },
  { name: "apple", image: "thumbs/apple.jpg", flipped: false },
  { name: "yes", image: "thumbs/yes.jpg", flipped: false },
  { name: "book", image: "thumbs/book.png", flipped: false },
  { name: "art", image: "thumbs/art.jpg", flipped: false },
  { name: "pumpkin", image: "thumbs/pumpkin.png", flipped: false },
  { name: "youtube", image: "thumbs/youtube.jpg", flipped: false }
];

const fruits = [
  { name: "apple", image: "thumbs/apple.jpg", flipped: false },
  { name: "banana", image: "thumbs/banana.jpg", flipped: false },
  { name: "blackberry", image: "thumbs/blackberry.jpg", flipped: false },
  { name: "cherry", image: "thumbs/cherry.jpg", flipped: false },
  { name: "coconut", image: "thumbs/coconut.png", flipped: false },
  { name: "grape", image: "thumbs/grape.jpg", flipped: false },
  { name: "grapefruit", image: "thumbs/grapefruit.jpg", flipped: false },
  { name: "kiwi", image: "thumbs/kiwi.jpg", flipped: false },
  { name: "lemon", image: "thumbs/lemon.png", flipped: false },
  { name: "lime", image: "thumbs/lime.jpg", flipped: false },
  { name: "mango", image: "thumbs/mango.jpg", flipped: false },
  { name: "melon", image: "thumbs/melon.jpg", flipped: false },
  { name: "watermelon", image: "thumbs/watermelon.jpg", flipped: false },
  { name: "mikan", image: "thumbs/mikan.jpg", flipped: false },
  { name: "orange", image: "thumbs/orange.jpg", flipped: false },
  { name: "peach", image: "thumbs/peach.jpg", flipped: false },
  { name: "pear", image: "thumbs/pear.jpg", flipped: false },
  { name: "plum", image: "thumbs/plum.png", flipped: false },
  { name: "raspberry", image: "thumbs/raspberry.jpg", flipped: false },
  { name: "strawberry", image: "thumbs/strawberry.jpg", flipped: false }
];

const animals = [
  { name: "cat", image: "thumbs/cat.jpg", flipped: false },
  { name: "rat", image: "thumbs/rat.jpg", flipped: false },
  { name: "bat", image: "thumbs/bat.jpg", flipped: false },
  { name: "dog", image: "thumbs/dog.jpg", flipped: false },
  { name: "bird", image: "thumbs/bird.jpg", flipped: false },
  { name: "zebra", image: "thumbs/zebra.jpg", flipped: false },
  { name: "elephant", image: "thumbs/elephant.png", flipped: false },
  { name: "lion", image: "thumbs/lion.jpg", flipped: false },
  { name: "shark", image: "thumbs/shark.jpg", flipped: false },
  { name: "jellyfish", image: "thumbs/jellyfish.jpg", flipped: false },
  { name: "tuna", image: "thumbs/tuna.png", flipped: false },
  { name: "salmon", image: "thumbs/salmon.jpg", flipped: false },
  { name: "frog", image: "thumbs/frog.jpg", flipped: false },
  { name: "wolf", image: "thumbs/wolf.png", flipped: false },
  { name: "ant", image: "thumbs/ant.jpg", flipped: false },
  { name: "panda", image: "thumbs/panda.jpg", flipped: false },
  { name: "bear", image: "thumbs/bear.jpg", flipped: false },
  { name: "parrot", image: "thumbs/parrot.jpg", flipped: false }
];

export { defaultDeck, fruits, animals };
