const colors = [
  { name: "red", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/red.jpg", flipped: false },
  // { name: "red", image: "thumbs/red.jpg", flipped: false },
  { name: "color-orange", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/color-orange.jpg", flipped: false },
  { name: "yellow", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/yellow.jpg", flipped: false },
  { name: "light-green", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/light-green.png", flipped: false },
  { name: "green", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/green.png", flipped: false },
  { name: "light-blue", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/light-blue.png", flipped: false },
  { name: "blue", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/blue.png", flipped: false },
  { name: "purple", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/purple.png", flipped: false },
  { name: "brown", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/brown.png", flipped: false },
  { name: "black", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/black.png", flipped: false },
  { name: "pink", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/pink.png", flipped: false },
  { name: "white", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/white.jpg", flipped: false }
];
const fruits = [
  { name: "apple", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/apple.jpg", flipped: false },
  { name: "banana", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/banana.jpg", flipped: false },
  { name: "blackberry", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/blackberry.jpg", flipped: false },
  { name: "cherry", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/cherry.jpg", flipped: false },
  { name: "coconut", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/coconut.png", flipped: false },
  { name: "grape", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/grape.jpg", flipped: false },
  { name: "grapefruit", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/grapefruit.jpg", flipped: false },
  { name: "kiwi", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/kiwi.jpg", flipped: false },
  { name: "lemon", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/lemon.png", flipped: false },
  { name: "lime", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/lime.jpg", flipped: false },
  { name: "mango", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/mango.jpg", flipped: false },
  { name: "melon", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/melon.jpg", flipped: false },
  { name: "watermelon", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/watermelon.jpg", flipped: false },
  { name: "mikan", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/mikan.jpg", flipped: false },
  { name: "orange", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/orange.jpg", flipped: false },
  { name: "peach", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/peach.jpg", flipped: false },
  { name: "pear", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/pear.jpg", flipped: false },
  { name: "plum", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/plum.png", flipped: false },
  { name: "raspberry", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/raspberry.jpg", flipped: false },
  { name: "strawberry", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/strawberry.jpg", flipped: false }
];

const animals = [
  { name: "cat", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/cat.jpg", flipped: false },
  { name: "rat", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/rat.jpg", flipped: false },
  { name: "bat", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/bat.jpg", flipped: false },
  { name: "dog", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/dog.jpg", flipped: false },
  { name: "bird", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/bird.jpg", flipped: false },
  { name: "zebra", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/zebra.jpg", flipped: false },
  { name: "elephant", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/elephant.png", flipped: false },
  { name: "lion", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/lion.jpg", flipped: false },
  { name: "shark", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/shark.jpg", flipped: false },
  { name: "jellyfish", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/jellyfish.jpg", flipped: false },
  { name: "tuna", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/tuna.png", flipped: false },
  { name: "salmon", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/salmon.jpg", flipped: false },
  { name: "frog", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/frog.jpg", flipped: false },
  { name: "wolf", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/wolf.png", flipped: false },
  { name: "ant", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/ant.jpg", flipped: false },
  { name: "panda", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/panda.jpg", flipped: false },
  { name: "bear", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/bear.jpg", flipped: false },
  { name: "parrot", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/parrot.jpg", flipped: false }
];

const testDeck = [
  { name: "pen", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/pen.jpg", flipped: false },
  { name: "David", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/David.jpg", flipped: false },
  { name: "dog", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/dog.jpg", flipped: false },
  { name: "bird", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/bird.jpg", flipped: false },
  { name: "rat", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/rat.jpg", flipped: false },
  { name: "duck", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/duck.jpg", flipped: false },
  { name: "cheetah", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/cheetah.jpg", flipped: false },
  { name: "elephant", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/elephant.png", flipped: false },
  { name: "fish", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/fish.png", flipped: false },
  { name: "horse", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/horse.jpg", flipped: false },
  { name: "jellyfish", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/jellyfish.jpg", flipped: false },
  { name: "shark", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/shark.jpg", flipped: false },
  { name: "lion", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/lion.jpg", flipped: false },
  { name: "zebra", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/zebra.jpg", flipped: false },
  { name: "raccoon", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/raccoon.jpg", flipped: false },
  { name: "sparrow", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/sparrow.jpg", flipped: false },
  { name: "pikachu", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/pikachu.jpg", flipped: false },
  { name: "donut", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/donut.jpg", flipped: false },
  { name: "cheese", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/cheese.jpg", flipped: false },
  { name: "apple", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/apple.jpg", flipped: false },
  { name: "yes", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/yes.jpg", flipped: false },
  { name: "book", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/book.png", flipped: false },
  { name: "art", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/art.jpg", flipped: false },
  { name: "pumpkin", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/pumpkin.png", flipped: false },
  { name: "youtube", image: "https://s3-ap-northeast-1.amazonaws.com/wmcooper2.com/images/thumbs/youtube.jpg", flipped: false }
];

export { testDeck, fruits, animals, colors };
